security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    users_in_memory:
      memory:
        users:
          admin:
            password: '%env(ADMIN_PASS)%'
            roles: [ 'ROLE_ADMIN' ]
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: users_in_memory
      form_login:
        login_path: login
        check_path: login
        enable_csrf: true
      logout:
        path: logout
        target: index

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
